HOTFIX: Fix SyntaxError in inventory drop callback - indentation issue
Line 1788 was dedented outside try block causing:
SyntaxError: expected 'except' or 'finally' block

Fixed by properly indenting all code within try block